services:
  db:
    image: postgres:16-alpine
    container_name: location-scouting-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: location_scouting
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  db-test:
    image: postgres:16-alpine
    container_name: location-scouting-db-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: location_scouting_test
    ports:
      - "5434:5432"

  minio:
    image: minio/minio
    container_name: location-scouting-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data


volumes:
  postgres_data:
  postgres_test_data:
  minio_data: